services:
  product-db:
    image: postgres:18-alpine
    container_name: product-db
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop123
    ports:
      - "5433:5432"
    volumes:
      - product-db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shop -d product_db"]
      interval: 5s
      timeout: 3s
      retries: 10

  auth-db:
    image: postgres:18-alpine
    container_name: auth-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth123
    ports:
      - "5434:5432"          # 5434 on your machine, so it doesn't clash with product-db (5433)
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U auth -d auth_db" ]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: shopsphere-redis
    command: ["redis-server", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  product-db-data:
  auth-db-data: