package com.shopsphere.auth.user;


import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.Instant;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

/**
 * A person who can log in. Stores the credentials and roles that the Authorization
 * Server needs; profile data (addresses, phone) will live in the User Service later.
 *
 * <p>The password is stored only as a salted hash, never as plain text.
 */
@Entity
@Table(name = "users")
@Getter
@Setter
@Builder
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor(access = AccessLevel.PRIVATE)
public class AppUser {

    /** Unique identifier, generated by the application. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Login name; unique across all users. */
    @Column(nullable = false, unique = true, length = 50)
    private String username;

    /** Contact email; unique across all users. */
    @Column(nullable = false, unique = true, length = 150)
    private String email;

    /** Delegating-encoder hash such as "{bcrypt}$2a$10$..."; never the raw password. */
    @Column(name = "password_hash", nullable = false, length = 100)
    private String passwordHash;

    /** Disabled users cannot log in (used to block accounts without deleting them). */
    @Builder.Default
    @Column(nullable = false)
    private boolean enabled = true;

    /** Role names without the ROLE_ prefix, e.g. ADMIN or CUSTOMER. */
    @Builder.Default
    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "user_roles", joinColumns = @JoinColumn(name = "user_id"))
    @Column(name = "role", nullable = false, length = 30)
    private Set<String> roles = new HashSet<>();

    /** Set automatically by Hibernate when the row is first inserted. */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;


    /** Refreshed automatically by Hibernate on every update. */
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

}
